/*
 * This source file was generated by the Gradle 'init' task
 */
package com.craftinginterpreters.lox;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LoxTest {
    @Test void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        assertEquals(2 + 2, 4);
    }
}
